/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class client_graphicLessInteract */

#ifndef _Included_client_graphicLessInteract
#define _Included_client_graphicLessInteract
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     client_graphicLessInteract
 * Method:    writetotty
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_client_graphicLessInteract_writetotty
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
