/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class JNIFoo */

#ifndef _Included_JNIFoo
#define _Included_JNIFoo
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     JNIFoo
 * Method:    nativeFoo
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_JNIFoo_nativeFoo
  (JNIEnv *, jobject);

/*
 * Class:     JNIFoo
 * Method:    open_term
 * Signature: ([C)I
 */
JNIEXPORT jint JNICALL Java_JNIFoo_open_1term
  (JNIEnv *, jobject, jcharArray);

/*
 * Class:     JNIFoo
 * Method:    write_char
 * Signature: (IC)I
 */
JNIEXPORT jint JNICALL Java_JNIFoo_write_1char
  (JNIEnv *, jobject, jint, jchar);

/*
 * Class:     JNIFoo
 * Method:    close_term
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_JNIFoo_close_1term
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
